version: 1

update_configs:
    -   package_manager: "python"
        directory: "/"
        update_schedule: "daily"
        default_reviewers:
            - "yannickkirschen"
        default_assignees:
            - "yannickkirschen"
